version: '3.3'

services:
  fastapi-app:
    container_name: fastapi-app
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXPOSED_PORT}:8081
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 8081 --workers 1 --timeout-keep-alive 1000"
    networks:
      - shared_network
    restart: always

networks:
  shared_network:
    external:
      name: shared_network
