version: '3.3'

services:
  fastapi-app:
    container_name: fastapi-app
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXPOSED_PORT}:5002
    command: bash -c "gunicorn --capture-output --enable-stdio-inheritance -w 1 --threads 4 -b 0.0.0.0:5002 app:app --timeout 1000 --log-config /home/fastapi-template/configs/gunicorn.conf"
    networks:
      - shared_network
    restart: always

networks:
  shared_network:
    external:
      name: shared_network